[package]
name = "kiku"
version = "0.1.0"
edition = "2021"
authors = ["RÃ©my Pierre Bushnell Clarke", "Ondra", "NightMare-V"]
license = "Mozilla Public License 2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
